color0 #43474a
color1 #ffb4ab
color2 #bdc8ce
color3 #c4c7c9
color4 #cfc3d0
color5 #bdc8ce
color6 #c4c7c9
color7 #e4e2e2
color8 #8d9194
color9 #ffb4ab
color10 #bdc8ce
color11 #c4c7c9
color12 #cfc3d0
color13 #bdc8ce
color14 #c4c7c9
color15 #e4e2e2

cursor                #e4e2e2
cursor_text_color     #131314
background            #131314
foreground            #e4e2e2
selection_foreground  #c3c7ca
selection_background  #43474a
active_border_color   #bdc8ce
inactive_border_color #43474a
url_color             #bdc8ce

active_tab_foreground   #273237
active_tab_background   #bdc8ce
inactive_tab_foreground #c3c7ca
inactive_tab_background #43474a
cursor_trail_color      #c3c7ca
