[general]
import = [ "/home/vidhyotha/.cache/wal/colors-alacritty.toml" ]

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style  = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style  = "Bold Italic"

[window.padding]
x = 10
y = 10

[window]
decorations = "full"

[cursor]
style            = "Block"
unfocused_hollow = true